site_name: Tesla Smart Charger Docs

docs_dir: docs

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.top
    - toc.integrate

plugins:
  - mermaid2

nav: []

# to navigate with `/site` content correctly
use_directory_urls: false
repo_url: https://github.com/codesquadnest/tesla-smart-charger
repo_name: codesquadnest/tesla-smart-charger
